// Devices
export const devices = [
  {
    id: 1,
    name: 'NIRS V5',
    defaultSamplingRate: 100,
    maxSamplingRate: 100,
    PDs: 1,
    PDNames: 'main',
    defaultIntensities: [180, 140, 140, 120, 120],
    defaultGain: ['HIGH', '100'],
    defaultChannels: ['O2Hb', 'HHb', 'THb', 'TOI'],
    LEDs: 5,
    preGains: ['LOW', 'HIGH', 'HIGHER'],
    driverName: 'STM32',
  },
  {
    id: 2,
    name: 'NIRS Beast',
    defaultSamplingRate: 100,
    maxSamplingRate: 1000,
    LEDs: 15,
    PDs: 1,
    PDNames: 'main',
    defaultIntensities: [180, 140, 140, 120, 120],
    defaultGain: ['HIGH', '100'],
    defaultChannels: ['O2Hb', 'HHb', 'THb', 'TOI'],
    preGains: ['LOW', 'HIGH', 'HIGHER'],
    driverName: 'tcp',
  },
];
